### ISSUE TITLE
Failing to return a named schedule can cause rescheduling loops.

### ISSUE THREAD

**Issue by peterwilsoncc** [iamsayan/migrate-wp-cron-to-action-scheduler#1]
Returning an interval without a named schedule (or an incorrectly named schedule) can cause rescheduling loops in plugins checking the schedule name is as expected. For a full explanation refer to https://github.com/humanmade/Cavalcade/issues/29

Notably, this happens with the syncing function in Jetpack which verifies the schedule is correct via name rather than the interval:

https://github.com/Automattic/jetpack/blob/4150c43136718a565a5d6bcd3acfc293d6db78a7/vendor/automattic/jetpack-sync/src/class-actions.php#L718-L733

For Cavalcade, I created a function for reverse lookup to prevent these rescheduling loops. On my over-engineered personal site, I noticed the constant rescheduling was blowing up the database table. Feel free to copy-paste :) 

https://github.com/humanmade/Cavalcade/blob/e8b1e9a08d242559f82fd9a0eb59e3ea2ef968f0/inc/namespace.php#L169-L189

**Comment by iamsayan** [comment]
Thanks for your help. It has been fixed now.
