### ISSUE TITLE
duplicate action scheduler

### ISSUE THREAD

**Issue by alexdhika** [iamsayan/migrate-wp-cron-to-action-scheduler#2]
many duplicate action scheduler ex : wpforms_email_summaries_cron

**Comment by iamsayan** [comment]
Hi @alexdhika 

Thanks for let me know. It might happen at the time of activation or deactivation of this plugin.

Please download the v1.0.4 version of the plugin from GitHub Repo and deactivate and remove old version and activate it.

Also, please remove all existing duplicate actions from Action Scheduler list page.

Let me know if problem still exists.

**Comment by alexdhika** [comment]
still duplicated until 180.000+ rows >__<

**Comment by iamsayan** [comment]
Issue fixed. Closing this issue.
