### ISSUE TITLE
Error Call Fuction

### ISSUE THREAD

**Issue by alexdhika** [iamsayan/migrate-wp-cron-to-action-scheduler#4]
PHP Fatal error:  Uncaught Error: Call to undefined function as_has_scheduled_action() in /var/www/sites1/htdocs/wp-content/plugins/migrate-wp-cron-to-action-scheduler/includes/Helpers/HelperFunctions.php:102

**Comment by iamsayan** [comment]
Issue fixed. Closing this issue.
